# Copyright (c) 2026, Salah and contributors
# For license information, please see license.txt
"""Custom fields and the role the cheque lifecycle adds to standard doctypes.

Created in code rather than shipped as fixtures because `cheque_events` runs on
Payment Entry submit and the fields must exist before any fixture sync could
have run, on both paths: `after_install` for a fresh site and a patch for sites
that already have the app. `create_custom_fields` is idempotent.

The role is created here too, not as a Role fixture: fixtures import *after*
doctype sync, so the DocPerm rows in mfg_cheque.json would reference a role that
does not exist yet and `migrate` would fail on a fresh site.
"""

import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_field, create_custom_fields
from frappe.permissions import add_permission, update_permission_property

CHEQUE_MANAGER = "Cheque Manager"

# A cheque manager posts Journal Entries and Payment Entries for real. The
# lifecycle actions deliberately do NOT use ignore_permissions, so the grant has
# to be genuine; see Cheque_Management_Implementation_Package.md section 13.1.
CHEQUE_MANAGER_PERMISSIONS = {
	"Journal Entry": ("read", "write", "create", "submit", "cancel"),
	"Payment Entry": ("read", "write", "create", "submit", "cancel"),
	"Account": ("read",),
	"Customer": ("read",),
	"Supplier": ("read",),
	"Sales Invoice": ("read",),
	"Purchase Invoice": ("read",),
}

CUSTOM_FIELDS = {
	"Mode of Payment": [
		{
			# Only drives form behaviour. What actually makes a Payment Entry a
			# cheque is a non-empty custom_mfg_cheque_type on it, so an
			# integration that never sets a Mode of Payment still works.
			"fieldname": "custom_mfg_is_cheque",
			"fieldtype": "Check",
			"label": "Is Cheque",
			"insert_after": "type",
			"default": "0",
			"description": (
				"Payment Entries using this Mode of Payment must name an MFG Cheque Type "
				"before they can be submitted, and generate an MFG Cheque record."
			),
		}
	],
	"Payment Entry": [
		{
			"fieldname": "custom_mfg_cheque_section",
			"fieldtype": "Section Break",
			"label": "Cheque",
			"insert_after": "reference_date",
			"collapsible": 0,
		},
		{
			# The cheque number and date are ERPNext's own reference_no /
			# reference_date ("Cheque/Reference No" / "Cheque/Reference Date").
			# Adding a second pair would let them disagree, and Bank Clearance
			# reads the native ones (bank_clearance.py:196-197).
			"fieldname": "custom_mfg_cheque_type",
			"fieldtype": "Link",
			"options": "MFG Cheque Type",
			"label": "Cheque Type",
			"insert_after": "custom_mfg_cheque_section",
			"description": "Decides which clearing account this cheque is captured into.",
		},
		{
			"fieldname": "custom_mfg_drawee_bank",
			"fieldtype": "Data",
			"label": "Drawee Bank",
			"insert_after": "custom_mfg_cheque_type",
			"depends_on": "eval:doc.payment_type == 'Receive'",
			"description": "The bank the customer's cheque is drawn on.",
		},
		{
			"fieldname": "custom_mfg_cheque_col_break",
			"fieldtype": "Column Break",
			"insert_after": "custom_mfg_drawee_bank",
		},
		{
			"fieldname": "custom_mfg_bank_account",
			"fieldtype": "Link",
			"options": "Account",
			"label": "Bank Account for Clearing",
			"insert_after": "custom_mfg_cheque_col_break",
			"description": (
				"The real bank account this cheque will eventually clear through. "
				"Not used at capture - the bank is only touched on Clear."
			),
		},
		{
			"fieldname": "custom_mfg_replaces",
			"fieldtype": "Link",
			"options": "MFG Cheque",
			"label": "Replaces Cheque",
			"insert_after": "custom_mfg_bank_account",
			"read_only": 1,
			"no_copy": 1,
			"description": "Set by the Replace action on a bounced cheque.",
		},
		{
			"fieldname": "custom_mfg_cancellation_reason",
			"fieldtype": "Small Text",
			"label": "Cheque Cancellation Reason",
			"insert_after": "custom_mfg_replaces",
			"allow_on_submit": 1,
			"depends_on": "custom_mfg_cheque_type",
			"description": "Optional audit reason copied to MFG Cheque if this Payment Entry is cancelled.",
		},
		{
			"fieldname": "custom_mfg_cheque",
			"fieldtype": "Link",
			"options": "MFG Cheque",
			"label": "MFG Cheque",
			"insert_after": "custom_mfg_replaces",
			"read_only": 1,
			"allow_on_submit": 1,
			"no_copy": 1,
			"description": "Set automatically on submit.",
		},
	],
	"Journal Entry": [
		{
			"fieldname": "custom_mfg_cheque",
			"fieldtype": "Link",
			"options": "MFG Cheque",
			"label": "MFG Cheque",
			"insert_after": "user_remark",
			"read_only": 1,
			"no_copy": 1,
			"description": "Set when this entry was generated by a cheque lifecycle action.",
		}
	],
}


def create_cheque_fields():
	create_custom_fields(CUSTOM_FIELDS, ignore_validate=True)
	create_cheque_permissions()


def create_cheque_accounting_dimension_fields():
	"""Create and normalize fields for dimensions that predate this app.

	ERPNext's dimension hook creates future fields. This companion handles the
	fresh-install and upgrade cases and makes the tracker fields visibly read-only
	because their values belong to the submitted capture Payment Entry.
	"""
	dimensions = frappe.get_all(
		"Accounting Dimension",
		fields=["fieldname", "label", "document_type"],
	)
	for dimension in dimensions:
		create_custom_field(
			"MFG Cheque",
			{
				"fieldname": dimension.fieldname,
				"label": dimension.label,
				"fieldtype": "Link",
				"options": dimension.document_type,
				"insert_after": "accounting_dimensions_section",
				"read_only": 1,
			},
			ignore_validate=True,
		)
		_normalize_cheque_dimension_field(
			dimension.fieldname, label=dimension.label, options=dimension.document_type
		)

	frappe.clear_cache(doctype="MFG Cheque")


def queue_cheque_accounting_dimension_sync(doc, method=None):
	"""Sync after commit so schema DDL cannot commit an Accounting Dimension save."""
	if frappe.flags.in_test:
		sync_cheque_accounting_dimension(doc.name)
		return
	frappe.enqueue(
		sync_cheque_accounting_dimension,
		dimension=doc.name,
		queue="long",
		enqueue_after_commit=True,
	)


def sync_cheque_accounting_dimension(dimension):
	"""Create or normalize one newly configured tracker dimension field."""
	doc = frappe.get_doc("Accounting Dimension", dimension)
	create_custom_field(
		"MFG Cheque",
		{
			"fieldname": doc.fieldname,
			"label": doc.label,
			"fieldtype": "Link",
			"options": doc.document_type,
			"insert_after": "accounting_dimensions_section",
			"read_only": 1,
		},
		ignore_validate=True,
	)
	_normalize_cheque_dimension_field(
		doc.fieldname, label=doc.label, options=doc.document_type
	)
	frappe.clear_cache(doctype="MFG Cheque")


def _normalize_cheque_dimension_field(fieldname, label, options):
	name = frappe.db.get_value("Custom Field", {"dt": "MFG Cheque", "fieldname": fieldname})
	if not name:
		return
	field = frappe.get_doc("Custom Field", name)
	changed = False
	for property_name, value in {
		"label": label,
		"options": options,
		"insert_after": "accounting_dimensions_section",
		"read_only": 1,
	}.items():
		if field.get(property_name) != value:
			field.set(property_name, value)
			changed = True
	if changed:
		field.flags.ignore_validate = True
		field.save()


def create_cheque_role():
	"""Create the role before DocType JSON is synchronized on a fresh install."""
	if frappe.db.exists("Role", CHEQUE_MANAGER):
		return

	role = frappe.new_doc("Role")
	role.role_name = CHEQUE_MANAGER
	role.desk_access = 1
	role.flags.ignore_permissions = True
	role.insert()


def create_cheque_permissions():
	"""Create the Cheque Manager role and its standard-DocType permissions.

	Frappe treats Custom DocPerm as a replacement for a DocType's standard
	permissions, so its permission helpers first copy the standard rows before
	adding ours. Calling this from both after_install and the patch is
	idempotent.
	"""
	create_cheque_role()

	for doctype, permission_types in CHEQUE_MANAGER_PERMISSIONS.items():
		filters = {"parent": doctype, "role": CHEQUE_MANAGER, "permlevel": 0, "if_owner": 0}
		if not frappe.db.exists("Custom DocPerm", filters):
			add_permission(doctype, CHEQUE_MANAGER, ptype=permission_types[0])

		for permission_type in permission_types:
			update_permission_property(doctype, CHEQUE_MANAGER, 0, permission_type, 1, validate=False)

	frappe.clear_cache()
